# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180521_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_author', models.CharField(max_length=255)),
                ('quote_message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quotes', to='login.User')),
                ('students', models.ManyToManyField(related_name='courses', to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_creator',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
