# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180521_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='students',
        ),
        migrations.AddField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='login.User'),
        ),
    ]
